version: '3.8'

services:
  db:
    build:
      context: ./docker/database
    container_name: api-rest-lbc
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: symapirestlbc
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    networks:
      - symfony

  symapirestlbc:
    build:
      context: ./docker/apache
    container_name: symapirestlbc_symfony
    depends_on:
      - db
    volumes:
      - .:/var/www/html/api-rest-lbc/
    ports:
      - 2520:8050
    restart: always
    entrypoint: sh /var/www/html/api-rest-lbc/docker/apache/start_server.sh
    networks:
      - symfony

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: api-rest-lbc_phpmyadmin
    links:
      - db
    restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: root
      MYSQL_ROOT_PASSWORD:
    networks:
      - symfony

networks:
  symfony:
